### ISSUE TITLE
Add Comments to the blog 

### ISSUE THREAD

**Issue by jamesekennedy** [JeremyMD/Blog#1]
### Setup
- Go to localhost:3000
- Click on "blog"
- Click on the first blog in the list
- It should display the blog
### Expected
- Below the blog should be a text area which allows me to enter some text as a comment on the blog.
- A button should allow me to save the comment
- Once the comment is saved, the comment should appear below the blog article.

**Comment by JeremyMD** [comment]
Hi James

I did setup the association with your help. 

The routing is now changed to have comments as a sub routing to posts. This enables comments to be added on the show page. A button was added to the page to save the comment. 

All saved comments will be display it at the bottom of the screen.

There is however a problem with the app still. It writes all the comment table columns to the comments  column. It also display a non existing blank row to screen.

**Comment by jamesekennedy** [comment]
Hi Jeremy

Can you commit up the app as it is and I'll see if I can see what is going
on.

James

On Mon, Mar 16, 2015 at 5:50 PM, JeremyMD notifications@github.com wrote:

> Reopened #1 https://github.com/JeremyMD/Blog/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JeremyMD/Blog/issues/1#event-255687841.

## 

Founder, RubberStamp.io
Ireland: +353 1 685 2267 US: 415 6709 710 Twitter: @jameskennedy
Curious about what we do?  Book a demonstration here
http://rubberstamp.appointlet.com.

**Comment by jamesekennedy** [comment]
Verified as complete
